-- MySQL Script generated by MySQL Workbench
-- Fri Aug 22 20:53:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLIENTE` ;

CREATE TABLE IF NOT EXISTS `CLIENTE` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIDADES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CIDADES` ;

CREATE TABLE IF NOT EXISTS `CIDADES` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  PRIMARY KEY (`id_cidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REGIOES_ATENDIDAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REGIOES_ATENDIDAS` ;

CREATE TABLE IF NOT EXISTS `REGIOES_ATENDIDAS` (
  `id_regiao` INT NOT NULL AUTO_INCREMENT,
  `id_cidade` INT NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_regiao`),
  INDEX `fk_REGIOES_ATENDIDAS_CIDADES_idx` (`id_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_REGIOES_ATENDIDAS_CIDADES`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `CIDADES` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENDERECO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ENDERECO` ;

CREATE TABLE IF NOT EXISTS `ENDERECO` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `complemento` VARCHAR(100) NULL,
  `id_regiao_atendida` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_ENDERECO_REGIOES_ATENDIDAS1_idx` (`id_regiao_atendida` ASC) VISIBLE,
  CONSTRAINT `fk_ENDERECO_REGIOES_ATENDIDAS1`
    FOREIGN KEY (`id_regiao_atendida`)
    REFERENCES `REGIOES_ATENDIDAS` (`id_regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENDERECO_CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ENDERECO_CLIENTE` ;

CREATE TABLE IF NOT EXISTS `ENDERECO_CLIENTE` (
  `id_endereco` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_endereco`, `id_cliente`),
  INDEX `fk_ENDERECO_has_CLIENTE_CLIENTE1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_ENDERECO_has_CLIENTE_ENDERECO1_idx` (`id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_ENDERECO_has_CLIENTE_ENDERECO1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `ENDERECO` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENDERECO_has_CLIENTE_CLIENTE1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `CLIENTE` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SABORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SABORES` ;

CREATE TABLE IF NOT EXISTS `SABORES` (
  `id_sabor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valor_adicional` VARCHAR(10) NULL,
  PRIMARY KEY (`id_sabor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BORDAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BORDAS` ;

CREATE TABLE IF NOT EXISTS `BORDAS` (
  `id_borda` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `valor_adicional` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_borda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MASSAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MASSAS` ;

CREATE TABLE IF NOT EXISTS `MASSAS` (
  `id_massa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `valor` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_massa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TAMANHOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAMANHOS` ;

CREATE TABLE IF NOT EXISTS `TAMANHOS` (
  `id_tamanho` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `preco_base` DECIMAL(10,2) NULL,
  `max_sabores` INT NULL,
  PRIMARY KEY (`id_tamanho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIZZA_PERSONALIZADA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZA_PERSONALIZADA` ;

CREATE TABLE IF NOT EXISTS `PIZZA_PERSONALIZADA` (
  `id_pizza_personaliza` INT NOT NULL AUTO_INCREMENT,
  `id_tamanho` INT NOT NULL,
  `id_massa` INT NOT NULL,
  `id_borda` INT NOT NULL,
  `max_sabores` INT NULL,
  `observacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_pizza_personaliza`),
  INDEX `fk_PIZZA_PERSONALIZADA_TAMANHOS1_idx` (`id_tamanho` ASC) VISIBLE,
  INDEX `fk_PIZZA_PERSONALIZADA_MASSAS1_idx` (`id_massa` ASC) VISIBLE,
  INDEX `fk_PIZZA_PERSONALIZADA_BORDAS1_idx` (`id_borda` ASC) VISIBLE,
  CONSTRAINT `fk_PIZZA_PERSONALIZADA_TAMANHOS1`
    FOREIGN KEY (`id_tamanho`)
    REFERENCES `TAMANHOS` (`id_tamanho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PIZZA_PERSONALIZADA_MASSAS1`
    FOREIGN KEY (`id_massa`)
    REFERENCES `MASSAS` (`id_massa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PIZZA_PERSONALIZADA_BORDAS1`
    FOREIGN KEY (`id_borda`)
    REFERENCES `BORDAS` (`id_borda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIZZA_SABORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZA_SABORES` ;

CREATE TABLE IF NOT EXISTS `PIZZA_SABORES` (
  `id_pizza_personalizada` INT NOT NULL,
  `id_sabor` INT NOT NULL,
  PRIMARY KEY (`id_pizza_personalizada`, `id_sabor`),
  INDEX `fk_PIZZA_SABORES_PIZZA_PERSONALIZADA1_idx` (`id_pizza_personalizada` ASC) VISIBLE,
  CONSTRAINT `fk_PIZZA_SABORES_SABORES1`
    FOREIGN KEY (`id_sabor`)
    REFERENCES `SABORES` (`id_sabor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PIZZA_SABORES_PIZZA_PERSONALIZADA1`
    FOREIGN KEY (`id_pizza_personalizada`)
    REFERENCES `PIZZA_PERSONALIZADA` (`id_pizza_personaliza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRODUTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PRODUTOS` ;

CREATE TABLE IF NOT EXISTS `PRODUTOS` (
  `id_produtos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT NOT NULL,
  PRIMARY KEY (`id_produtos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARRINHO_ITENS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARRINHO_ITENS` ;

CREATE TABLE IF NOT EXISTS `CARRINHO_ITENS` (
  `id_carrinho` INT NOT NULL AUTO_INCREMENT,
  `id_pizza_personalizada` INT NOT NULL,
  `id_produtos` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  `data_adicionado` DATE NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_carrinho`),
  INDEX `fk_CARRINHO_ITENS_PIZZA_PERSONALIZADA1_idx` (`id_pizza_personalizada` ASC) VISIBLE,
  INDEX `fk_CARRINHO_ITENS_PRODUTOS_EXTRA1_idx` (`id_produtos` ASC) VISIBLE,
  INDEX `fk_CARRINHO_ITENS_CLIENTE1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_CARRINHO_ITENS_PIZZA_PERSONALIZADA1`
    FOREIGN KEY (`id_pizza_personalizada`)
    REFERENCES `PIZZA_PERSONALIZADA` (`id_pizza_personaliza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARRINHO_ITENS_PRODUTOS_EXTRA1`
    FOREIGN KEY (`id_produtos`)
    REFERENCES `PRODUTOS` (`id_produtos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARRINHO_ITENS_CLIENTE1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `CLIENTE` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CUPONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CUPONS` ;

CREATE TABLE IF NOT EXISTS `CUPONS` (
  `id_cupom` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NULL,
  `descricao` VARCHAR(100) NULL,
  `tipo_desconto` VARCHAR(50) NOT NULL,
  `valor_desconto` DECIMAL(10,2) NULL,
  `limite_usuarios` INT NOT NULL,
  `data_expiracao` DATE NOT NULL,
  PRIMARY KEY (`id_cupom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CHECKOUT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CHECKOUT` ;

CREATE TABLE IF NOT EXISTS `CHECKOUT` (
  `id_checkout` INT NOT NULL AUTO_INCREMENT,
  `id_carrinho` INT NOT NULL,
  `id_cupom` INT NOT NULL,
  PRIMARY KEY (`id_checkout`),
  INDEX `fk_CHECKOUT_CUPONS1_idx` (`id_cupom` ASC) VISIBLE,
  INDEX `fk_CHECKOUT_CARRINHO_ITENS1_idx` (`id_carrinho` ASC) VISIBLE,
  CONSTRAINT `fk_CHECKOUT_CUPONS1`
    FOREIGN KEY (`id_cupom`)
    REFERENCES `CUPONS` (`id_cupom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHECKOUT_CARRINHO_ITENS1`
    FOREIGN KEY (`id_carrinho`)
    REFERENCES `CARRINHO_ITENS` (`id_carrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STATUS_PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STATUS_PEDIDO` ;

CREATE TABLE IF NOT EXISTS `STATUS_PEDIDO` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PEDIDOS_CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PEDIDOS_CLIENTE` ;

CREATE TABLE IF NOT EXISTS `PEDIDOS_CLIENTE` (
  `id_pedido_cliente` INT NOT NULL AUTO_INCREMENT,
  `id_checkout` INT NOT NULL,
  `id_status` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pedido_cliente`, `id_checkout`, `id_status`),
  INDEX `fk_PEDIDOS_CLIENTE_CHECKOUT1_idx` (`id_checkout` ASC) VISIBLE,
  INDEX `fk_PEDIDOS_CLIENTE_STATUS_PEDIDO1_idx` (`id_status` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOS_CLIENTE_CHECKOUT1`
    FOREIGN KEY (`id_checkout`)
    REFERENCES `CHECKOUT` (`id_checkout`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDOS_CLIENTE_STATUS_PEDIDO1`
    FOREIGN KEY (`id_status`)
    REFERENCES `STATUS_PEDIDO` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAGAMENTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PAGAMENTOS` ;

CREATE TABLE IF NOT EXISTS `PAGAMENTOS` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `id_checkout` INT NOT NULL,
  `metodo` VARCHAR(50) NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(30) NULL,
  `data_pagamento` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_PAGAMENTOS_CHECKOUT1_idx` (`id_checkout` ASC) VISIBLE,
  PRIMARY KEY (`id_pagamento`),
  CONSTRAINT `fk_PAGAMENTOS_CHECKOUT1`
    FOREIGN KEY (`id_checkout`)
    REFERENCES `CHECKOUT` (`id_checkout`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FUNCIONARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FUNCIONARIOS` ;

CREATE TABLE IF NOT EXISTS `FUNCIONARIOS` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(30) NULL,
  `email` VARCHAR(100) NULL,
  `cpf` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PEDIDO_FUNCIONARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PEDIDO_FUNCIONARIO` ;

CREATE TABLE IF NOT EXISTS `PEDIDO_FUNCIONARIO` (
  `id_pedido` INT NOT NULL,
  `id_funcionario` INT NOT NULL,
  `papel` ENUM('Atendente', 'Pizzaiolo', 'Entregador') NULL,
  PRIMARY KEY (`id_pedido`, `id_funcionario`),
  INDEX `fk_PEDIDOS_CLIENTE_has_FUNCIONARIOS_FUNCIONARIOS1_idx` (`id_funcionario` ASC) VISIBLE,
  INDEX `fk_PEDIDOS_CLIENTE_has_FUNCIONARIOS_PEDIDOS_CLIENTE1_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOS_CLIENTE_has_FUNCIONARIOS_PEDIDOS_CLIENTE1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `PEDIDOS_CLIENTE` (`id_pedido_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDOS_CLIENTE_has_FUNCIONARIOS_FUNCIONARIOS1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `FUNCIONARIOS` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
